blank_issues_enabled: false
contact_links:
  - name: GmodStore Moderative Help
    url: https://www.gmodstore.com/help/tickets/create/site
    about: Please create a ticket here if you need help with the GmodStore platform
  - name: GmodStore Community Help
    url: https://www.gmodstore.com/community
    about: For any other questions 