blank_issues_enabled: false
contact_links:
  - name: GmodStore Moderative Help
    url: https://github.community/
    about: Please create a ticket here if you need help with the GmodStore platform
  - name: GmodStore Community Help
    url: https://bounty.github.com/
    about: For any other questions 